-- Phoenix wiki PH -> NM lookup, updated 2026-10-04.
-- Partial: 308 IDs / 230 NMs. Full entity ServerId keys.
return {
    [16793645] = { nm_slug = "Serra", zone = "Bibiki Bay", placeholder_name = "Jagil" },
    [16793741] = { nm_slug = "Intulo", zone = "Bibiki Bay", placeholder_name = "Eft" },
    [16798055] = { nm_slug = "Bonnacon", zone = "Uleguerand Range", placeholder_name = "Buffalo" },
    [16806171] = { nm_slug = "Ambusher_Antlion", zone = "Attohwa Chasm", placeholder_name = "Trench Antlion" },
    [16826507] = { nm_slug = "Swashstox_Beadblinker", zone = "Newton Movalpolos", placeholder_name = "Goblin Swordsman" },
    [16826514] = { nm_slug = "Swashstox_Beadblinker", zone = "Newton Movalpolos", placeholder_name = "Goblin Swordsman" },
    [16875711] = { nm_slug = "Megalobugard", zone = "Lufaise Meadows", placeholder_name = "Gigantobugard" },
    [16875720] = { nm_slug = "Megalobugard", zone = "Lufaise Meadows", placeholder_name = "Gigantobugard" },
    [16875739] = { nm_slug = "Megalobugard", zone = "Lufaise Meadows", placeholder_name = "Gigantobugard" },
    [16900305] = { nm_slug = "Aiatar", zone = "Riverne - Site #A01", placeholder_name = "Flamedrake" },
    [16941089] = { nm_slug = "Gosspix_Blabberlips", zone = "Dynamis - Buburimu", placeholder_name = "Vanguard Enchanter" },
    [16941103] = { nm_slug = "Flamecaller_Zoeqdoq", zone = "Dynamis - Buburimu", placeholder_name = "Vanguard Mesmerizer" },
    [16941113] = { nm_slug = "Elvaansticker_Bxafraff", zone = "Dynamis - Buburimu", placeholder_name = "Vanguard Impaler" },
    [16941124] = { nm_slug = "Hamfist_Gukhbuk", zone = "Dynamis - Buburimu", placeholder_name = "Vanguard Grappler" },
    [16941127] = { nm_slug = "Lyncean_Juwgneg", zone = "Dynamis - Buburimu", placeholder_name = "Vanguard Predator" },
    [16941139] = { nm_slug = "QuPho_Bloodspiller", zone = "Dynamis - Buburimu", placeholder_name = "Vanguard Vindicator" },
    [16941142] = { nm_slug = "GiBhe_Fleshfeaster", zone = "Dynamis - Buburimu", placeholder_name = "Vanguard Constable" },
    [16941162] = { nm_slug = "TeZha_Ironclad", zone = "Dynamis - Buburimu", placeholder_name = "Vanguard Defender" },
    [16941184] = { nm_slug = "Ree_Nata_The_Melomanic", zone = "Dynamis - Buburimu", placeholder_name = "Vanguard Chanter" },
    [16941185] = { nm_slug = "Koo_Rahi_The_Levinblade", zone = "Dynamis - Buburimu", placeholder_name = "Vanguard Persecutor" },
    [16941202] = { nm_slug = "Doo_Peku_The_Fleetfoot", zone = "Dynamis - Buburimu", placeholder_name = "Vanguard Assassin" },
    [16941203] = { nm_slug = "Baa_Dava_The_Bibliophage", zone = "Dynamis - Buburimu", placeholder_name = "Vanguard Oracle" },
    [16986196] = { nm_slug = "Zoraal_Jas_Pkuucha", zone = "Wajaom Woodlands", placeholder_name = "Lesser Colibri" },
    [16986377] = { nm_slug = "Jaded_Jody", zone = "Wajaom Woodlands", placeholder_name = "Great Ameretat" },
    [16998654] = { nm_slug = "Bloody_Bones", zone = "Arrapago Reef", placeholder_name = "Draugar Servant" },
    [17027146] = { nm_slug = "Energetic_Eruca", zone = "Mount Zhayolm", placeholder_name = "Magmatic Eruca" },
    [17043553] = { nm_slug = "Zizzy_Zillah", zone = "Mamook", placeholder_name = "Ziz" },
    [17055955] = { nm_slug = "Bluestreak_Gyugyuroon", zone = "Aydeewa Subterrane", placeholder_name = "Qiqirn Archaeologist" },
    [17100873] = { nm_slug = "Peallaidh", zone = "Caedarva Mire", placeholder_name = "Wild Karakul" },
    [17187026] = { nm_slug = "Fungus_Beetle", zone = "West Ronfaure", placeholder_name = "Scarab Beetle" },
    [17187110] = { nm_slug = "Jaggedy-Eared_Jack", zone = "West Ronfaure", placeholder_name = "Forest Hare" },
    [17191194] = { nm_slug = "Bigmouth_Billy", zone = "East Ronfaure", placeholder_name = "Carrion Worm" },
    [17191195] = { nm_slug = "Bigmouth_Billy", zone = "East Ronfaure", placeholder_name = "Carrion Worm" },
    [17195143] = { nm_slug = "Lumbering_Lambert", zone = "La Theine Plateau", placeholder_name = "Battering Ram" },
    [17195258] = { nm_slug = "Tumbling_Truffle", zone = "La Theine Plateau", placeholder_name = "Poison Funguar" },
    [17195316] = { nm_slug = "Lumbering_Lambert", zone = "La Theine Plateau", placeholder_name = "Battering Ram" },
    [17195317] = { nm_slug = "Bloodtear_Baldurf", zone = "La Theine Plateau", placeholder_name = "Lumbering Lambert" },
    [17199434] = { nm_slug = "Valkurm_Emperor", zone = "Valkurm Dunes", placeholder_name = "Damselfly" },
    [17199562] = { nm_slug = "Golden_Bat", zone = "Valkurm Dunes", placeholder_name = "Giant Bat" },
    [17203447] = { nm_slug = "Fradubio", zone = "Jugner Forest", placeholder_name = "Fraelissa" },
    [17203581] = { nm_slug = "Panzer_Percival", zone = "Jugner Forest", placeholder_name = "Stag Beetle" },
    [17203637] = { nm_slug = "Panzer_Percival", zone = "Jugner Forest", placeholder_name = "Stag Beetle" },
    [17211536] = { nm_slug = "Stinging_Sophie", zone = "North Gustaberg", placeholder_name = "Maneating Hornet" },
    [17211560] = { nm_slug = "Stinging_Sophie", zone = "North Gustaberg", placeholder_name = "Maneating Hornet" },
    [17211701] = { nm_slug = "Maighdean_Uaine", zone = "North Gustaberg", placeholder_name = "Walking Sapling" },
    [17215867] = { nm_slug = "Leaping_Lizzy", zone = "South Gustaberg", placeholder_name = "Rock Lizard" },
    [17219791] = { nm_slug = "Stray_Mary", zone = "Konschtat Highlands", placeholder_name = "Mad Sheep" },
    [17219885] = { nm_slug = "Rampaging_Ram", zone = "Konschtat Highlands", placeholder_name = "Tremor Ram" },
    [17219928] = { nm_slug = "Stray_Mary", zone = "Konschtat Highlands", placeholder_name = "Mad Sheep" },
    [17219987] = { nm_slug = "Rampaging_Ram", zone = "Konschtat Highlands", placeholder_name = "Tremor Ram" },
    [17223888] = { nm_slug = "Jolly_Green", zone = "Pashhow Marshlands", placeholder_name = "Goobbue" },
    [17224014] = { nm_slug = "Bloodpool_Vorax", zone = "Pashhow Marshlands", placeholder_name = "Thread Leech" },
    [17227968] = { nm_slug = "Black_Triple_Stars", zone = "Rolanberry Fields", placeholder_name = "Midnight Wings" },
    [17227988] = { nm_slug = "Black_Triple_Stars", zone = "Rolanberry Fields", placeholder_name = "Midnight Wings" },
    [17228235] = { nm_slug = "Drooling_Daisy", zone = "Rolanberry Fields", placeholder_name = "Ochu" },
    [17231970] = { nm_slug = "Nue", zone = "Beaucedine Glacier", placeholder_name = "Tundra Tiger" },
    [17232078] = { nm_slug = "Gargantua", zone = "Beaucedine Glacier", placeholder_name = "Stone Golem" },
    [17236174] = { nm_slug = "Shadow_Eye", zone = "Xarcabard", placeholder_name = "Evil Eye" },
    [17240371] = { nm_slug = "Frostmane", zone = "Cape Teriggan", placeholder_name = "Greater Manticore" },
    [17240372] = { nm_slug = "Frostmane", zone = "Cape Teriggan", placeholder_name = "Greater Manticore" },
    [17240373] = { nm_slug = "Frostmane", zone = "Cape Teriggan", placeholder_name = "Greater Manticore" },
    [17240374] = { nm_slug = "Frostmane", zone = "Cape Teriggan", placeholder_name = "Greater Manticore" },
    [17244395] = { nm_slug = "Dune_Widow", zone = "Eastern Altepa Desert", placeholder_name = "Giant Spider" },
    [17248467] = { nm_slug = "Tom_Tit_Tat", zone = "West Sarutabaruta", placeholder_name = "Mandragora" },
    [17248485] = { nm_slug = "Tom_Tit_Tat", zone = "West Sarutabaruta", placeholder_name = "Mandragora" },
    [17248516] = { nm_slug = "Nunyenunc", zone = "West Sarutabaruta", placeholder_name = "Carrion Crow" },
    [17252656] = { nm_slug = "Spiny_Spipi", zone = "East Sarutabaruta", placeholder_name = "Crawler" },
    [17256560] = { nm_slug = "Serpopard_Ishtar", zone = "Tahrongi Canyon", placeholder_name = "Wild Dhalmel" },
    [17256686] = { nm_slug = "Serpopard_Ishtar", zone = "Tahrongi Canyon", placeholder_name = "Wild Dhalmel" },
    [17260906] = { nm_slug = "Helldiver", zone = "Buburimu Peninsula", placeholder_name = "Zu" },
    [17261002] = { nm_slug = "Buburimboo", zone = "Buburimu Peninsula", placeholder_name = "Shoal Pugil" },
    [17268849] = { nm_slug = "Deadly_Dodo", zone = "Sauromugue Champaign", placeholder_name = "Tabar Beak" },
    [17276963] = { nm_slug = "Nightmare_Vase", zone = "Ro'Maeve", placeholder_name = "Magic Flagon" },
    [17276972] = { nm_slug = "Nightmare_Vase", zone = "Ro'Maeve", placeholder_name = "Magic Flagon" },
    [17276981] = { nm_slug = "Nightmare_Vase", zone = "Ro'Maeve", placeholder_name = "Magic Flagon" },
    [17276991] = { nm_slug = "Nightmare_Vase", zone = "Ro'Maeve", placeholder_name = "Magic Flagon" },
    [17281148] = { nm_slug = "Mischievous_Micholas", zone = "Yuhtunga Jungle", placeholder_name = "Young Opo-Opo" },
    [17289559] = { nm_slug = "Cactuar_Cantautor", zone = "Western Altepa Desert", placeholder_name = "Cactuar" },
    [17309938] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309939] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309940] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309941] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309942] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309943] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309944] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309945] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309946] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309947] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309948] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309949] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309950] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309951] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309952] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17309953] = { nm_slug = "Despot", zone = "Ru'Aun Gardens", placeholder_name = "Groundskeeper" },
    [17326100] = { nm_slug = "GuNha_Wallstormer", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Vindicator" },
    [17326109] = { nm_slug = "NaHya_Floodmaker", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Protector" },
    [17326121] = { nm_slug = "JiFhu_Infiltrator", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Purloiner" },
    [17326134] = { nm_slug = "GaFho_Venomtouch", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Constable" },
    [17326139] = { nm_slug = "TaHyu_Gallanthunter", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Vigilante" },
    [17326150] = { nm_slug = "NuBhi_Spiraleye", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Minstrel" },
    [17326153] = { nm_slug = "DeBho_Pyrohand", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Thaumaturge" },
    [17326157] = { nm_slug = "GoTyo_Magenapper", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Drakekeeper" },
    [17326171] = { nm_slug = "MuGha_Legionkiller", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Defender" },
    [17326177] = { nm_slug = "SoGho_Adderhandler", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Beasttender" },
    [17326189] = { nm_slug = "JiKhu_Towercleaver", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Hatamoto" },
    [17326194] = { nm_slug = "MiRhe_Whisperblade", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Kusa" },
    [17326199] = { nm_slug = "BeZhe_Keeprazer", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Undertaker" },
    [17326211] = { nm_slug = "Humegutter_Adzjbadj", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Footsoldier" },
    [17326215] = { nm_slug = "Jeunoraider_Gepkzip", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Backstabber" },
    [17326217] = { nm_slug = "Cobraclaw_Buchzvotch", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Grappler" },
    [17326221] = { nm_slug = "Wraithdancer_Gidbnod", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Amputator" },
    [17326227] = { nm_slug = "Galkarider_Retzpratz", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Predator" },
    [17326231] = { nm_slug = "Deathcaller_Bidfbid", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Dollmaster" },
    [17326236] = { nm_slug = "Spinalsucker_Galflmall", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Vexer" },
    [17326241] = { nm_slug = "Lockbuster_Zapdjipp", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Pillager" },
    [17326247] = { nm_slug = "Heavymail_Djidzbad", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Trooper" },
    [17326254] = { nm_slug = "Elvaanlopper_Grokdok", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Gutslasher" },
    [17326257] = { nm_slug = "Skinmask_Ugghfogg", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Neckchopper" },
    [17326261] = { nm_slug = "Taruroaster_Biggsjig", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Mesmerizer" },
    [17326263] = { nm_slug = "Mithraslaver_Debhabob", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Hawker" },
    [17326267] = { nm_slug = "Ultrasonic_Zeknajak", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Bugler" },
    [17326271] = { nm_slug = "Drakefeast_Wubmfub", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Impaler" },
    [17326288] = { nm_slug = "Xaa_Chau_The_Roctalon", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Sentinel" },
    [17326294] = { nm_slug = "Koo_Saxu_The_Everfast", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Priest" },
    [17326298] = { nm_slug = "Bhuu_Wjato_The_Firepool", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Prelate" },
    [17326302] = { nm_slug = "Caa_Xaza_The_Madpiercer", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Visionary" },
    [17326305] = { nm_slug = "Maa_Zaua_The_Wyrmkeeper", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Partisan" },
    [17326311] = { nm_slug = "Ryy_Qihi_The_Idolrobber", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Liberator" },
    [17326321] = { nm_slug = "Nee_Huxa_The_Judgmental", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Inciter" },
    [17326324] = { nm_slug = "Kuu_Xuka_The_Nimble", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Assassin" },
    [17326326] = { nm_slug = "Soo_Jopo_The_Fiendking", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Ogresoother" },
    [17326343] = { nm_slug = "Knii_Hoqo_The_Bisector", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Persecutor" },
    [17326345] = { nm_slug = "Puu_Timu_The_Phantasmal", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Oracle" },
    [17326372] = { nm_slug = "Moltenox_Stubthumbs", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Smithy" },
    [17326377] = { nm_slug = "Droprix_Granitepalms", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Pitfighter" },
    [17326390] = { nm_slug = "Brewnix_Bittypupils", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Alchemist" },
    [17326395] = { nm_slug = "Ascetox_Ratgums", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Shaman" },
    [17326400] = { nm_slug = "Gibberox_Pimplebeak", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Enchanter" },
    [17326403] = { nm_slug = "Swypestix_Tigershins", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Hitman" },
    [17326413] = { nm_slug = "Ruffbix_Jumbolobes", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Armorer" },
    [17326419] = { nm_slug = "Draklix_Scalecrust", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Dragontamer" },
    [17326425] = { nm_slug = "Tocktix_Thinlids", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Tinkerer" },
    [17326437] = { nm_slug = "Routsix_Rubbertendon", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Pathfinder" },
    [17326444] = { nm_slug = "Morblox_Chubbychin", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Necromancer" },
    [17326451] = { nm_slug = "Whistrix_Toadthroat", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Maestro" },
    [17326457] = { nm_slug = "Slinkix_Trufflesniff", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Ambusher" },
    [17326461] = { nm_slug = "Shisox_Widebrow", zone = "Dynamis - Beaucedine", placeholder_name = "Vanguard Ronin" },
    [17330222] = { nm_slug = "Marquis_Decarabia", zone = "Dynamis - Xarcabard", placeholder_name = "Kindred Bard" },
    [17330331] = { nm_slug = "Prince_Seere", zone = "Dynamis - Xarcabard", placeholder_name = "Kindred White Mage" },
    [17330333] = { nm_slug = "Marquis_Orias", zone = "Dynamis - Xarcabard", placeholder_name = "Kindred Black Mage" },
    [17330352] = { nm_slug = "Duke_Berith", zone = "Dynamis - Xarcabard", placeholder_name = "Kindred Red Mage" },
    [17330359] = { nm_slug = "Marquis_Sabnak", zone = "Dynamis - Xarcabard", placeholder_name = "Kindred Paladin" },
    [17330376] = { nm_slug = "Count_Zaebos", zone = "Dynamis - Xarcabard", placeholder_name = "Kindred Warrior" },
    [17330388] = { nm_slug = "Marquis_Andras", zone = "Dynamis - Xarcabard", placeholder_name = "Kindred Beastmaster" },
    [17330414] = { nm_slug = "Marquis_Cimeries", zone = "Dynamis - Xarcabard", placeholder_name = "Kindred Ranger" },
    [17330418] = { nm_slug = "King_Zagan", zone = "Dynamis - Xarcabard", placeholder_name = "Kindred Dragoon" },
    [17330427] = { nm_slug = "Duke_Scox", zone = "Dynamis - Xarcabard", placeholder_name = "Kindred Dark Knight" },
    [17330450] = { nm_slug = "Marquis_Gamygyn", zone = "Dynamis - Xarcabard", placeholder_name = "Kindred Ninja" },
    [17330479] = { nm_slug = "Marquis_Nebiros", zone = "Dynamis - Xarcabard", placeholder_name = "Kindred Summoner" },
    [17354825] = { nm_slug = "Hundredscar_Hajwaj", zone = "Fort Ghelsba", placeholder_name = "Orcish Grappler" },
    [17358928] = { nm_slug = "Ashmaker_Gotblut", zone = "Yughott Grotto", placeholder_name = "Orcish Grunt" },
    [17358929] = { nm_slug = "Ashmaker_Gotblut", zone = "Yughott Grotto", placeholder_name = "Orcish Stonechucker" },
    [17363180] = { nm_slug = "BuGhi_Howlblade", zone = "Palborough Mines", placeholder_name = "Copper Beetle" },
    [17363205] = { nm_slug = "ZiGhi_Boneeater", zone = "Palborough Mines", placeholder_name = "Veteran Quadav" },
    [17371296] = { nm_slug = "Juu_Duzu_The_Whirlwind", zone = "Giddeus", placeholder_name = "Yagudo Persecutor" },
    [17371513] = { nm_slug = "Hoo_Mjuu_The_Torrent", zone = "Giddeus", placeholder_name = "Yagudo Mendicant" },
    [17371577] = { nm_slug = "Vuu_Puqu_The_Beguiler", zone = "Giddeus", placeholder_name = "Yagudo Piper" },
    [17379426] = { nm_slug = "DaDha_Hundredmask", zone = "Beadeaux", placeholder_name = "Copper Quadav" },
    [17379447] = { nm_slug = "GeDha_Evileye", zone = "Beadeaux", placeholder_name = "Old Quadav" },
    [17379562] = { nm_slug = "ZoKhu_Blackcloud", zone = "Beadeaux", placeholder_name = "Zircon Quadav" },
    [17379625] = { nm_slug = "GaBhu_Unvanquished", zone = "Beadeaux", placeholder_name = "Emerald Quadav" },
    [17387560] = { nm_slug = "Hawkeyed_Dnatbat", zone = "Davoi", placeholder_name = "Orcish Cursemaker" },
    [17387563] = { nm_slug = "Hawkeyed_Dnatbat", zone = "Davoi", placeholder_name = "Orcish Cursemaker" },
    [17387578] = { nm_slug = "Steelbiter_Gudrud", zone = "Davoi", placeholder_name = "Orcish Impaler" },
    [17387605] = { nm_slug = "Tigerbane_Bakdak", zone = "Davoi", placeholder_name = "War Lizard" },
    [17387623] = { nm_slug = "Poisonhand_Gnadgad", zone = "Davoi", placeholder_name = "Orcish Beastrider" },
    [17387624] = { nm_slug = "Poisonhand_Gnadgad", zone = "Davoi", placeholder_name = "Orcish Nightraider" },
    [17387638] = { nm_slug = "Poisonhand_Gnadgad", zone = "Davoi", placeholder_name = "Orcish Impaler" },
    [17387919] = { nm_slug = "Blubbery_Bulge", zone = "Davoi", placeholder_name = "Davoi Mush" },
    [17395798] = { nm_slug = "Mee_Deggi_The_Punisher", zone = "Castle Oztroja", placeholder_name = "Yagudo Drummer" },
    [17395799] = { nm_slug = "Mee_Deggi_The_Punisher", zone = "Castle Oztroja", placeholder_name = "Yagudo Interrogator" },
    [17395867] = { nm_slug = "Quu_Domi_The_Gallant", zone = "Castle Oztroja", placeholder_name = "Yagudo Herald" },
    [17395868] = { nm_slug = "Quu_Domi_The_Gallant", zone = "Castle Oztroja", placeholder_name = "Yagudo Oracle" },
    [17395950] = { nm_slug = "Yaa_Haqa_The_Profane", zone = "Castle Oztroja", placeholder_name = "Yagudo Zealot" },
    [17395953] = { nm_slug = "Yaa_Haqa_The_Profane", zone = "Castle Oztroja", placeholder_name = "Yagudo Prior" },
    [17403938] = { nm_slug = "Ellyllon", zone = "The Boyahda Tree", placeholder_name = "Death Cap" },
    [17403999] = { nm_slug = "Aquarius", zone = "The Boyahda Tree", placeholder_name = "Robber Crab" },
    [17404004] = { nm_slug = "Aquarius", zone = "The Boyahda Tree", placeholder_name = "Robber Crab" },
    [17404027] = { nm_slug = "Unut", zone = "The Boyahda Tree", placeholder_name = "Moss Eater" },
    [17404043] = { nm_slug = "Unut", zone = "The Boyahda Tree", placeholder_name = "Moss Eater" },
    [17404053] = { nm_slug = "Unut", zone = "The Boyahda Tree", placeholder_name = "Moss Eater" },
    [17404060] = { nm_slug = "Unut", zone = "The Boyahda Tree", placeholder_name = "Moss Eater" },
    [17404330] = { nm_slug = "Voluptuous_Vivian", zone = "The Boyahda Tree", placeholder_name = "Demonic Rose" },
    [17420383] = { nm_slug = "Polybotes", zone = "Middle Delkfutt's Tower", placeholder_name = "Giant Gatekeeper" },
    [17420419] = { nm_slug = "Rhoitos", zone = "Middle Delkfutt's Tower", placeholder_name = "Giant Guard" },
    [17420556] = { nm_slug = "Rhoikos", zone = "Middle Delkfutt's Tower", placeholder_name = "Gigas Quarrier" },
    [17420593] = { nm_slug = "Ogygos", zone = "Middle Delkfutt's Tower", placeholder_name = "Gigas Wallwatcher" },
    [17424474] = { nm_slug = "Ixtab", zone = "Upper Delkfutt's Tower", placeholder_name = "Phasma UDT" },
    [17424511] = { nm_slug = "Ixtab", zone = "Upper Delkfutt's Tower", placeholder_name = "Phasma UDT" },
    [17428551] = { nm_slug = "Sozu_Sarberry", zone = "Temple of Uggalepih", placeholder_name = "Tonberry Cutter" },
    [17428608] = { nm_slug = "Sozu_Terberry", zone = "Temple of Uggalepih", placeholder_name = "Tonberry Harrier" },
    [17428675] = { nm_slug = "Tonberry_Kinq", zone = "Temple of Uggalepih", placeholder_name = "Tonberry Dismayer" },
    [17432622] = { nm_slug = "Celeste-Eyed_Tozberry", zone = "Den of Rancor", placeholder_name = "Tonberry Trailer" },
    [17432638] = { nm_slug = "Friar_Rush", zone = "Den of Rancor", placeholder_name = "Bifrons DoR" },
    [17432662] = { nm_slug = "Carmine-Tailed_Janberry", zone = "Den of Rancor", placeholder_name = "Tonberry Imprecator" },
    [17432671] = { nm_slug = "Carmine-Tailed_Janberry", zone = "Den of Rancor", placeholder_name = "Tonberry Imprecator" },
    [17432787] = { nm_slug = "Tawny-Fingered_Mugberry", zone = "Den of Rancor", placeholder_name = "Tonberry Slasher" },
    [17432820] = { nm_slug = "Bistre-Hearted_Malberry", zone = "Den of Rancor", placeholder_name = "Tonberry Beleaguerer" },
    [17432973] = { nm_slug = "Ogama", zone = "Den of Rancor", placeholder_name = "Doom Toad" },
    [17432979] = { nm_slug = "Ogama", zone = "Den of Rancor", placeholder_name = "Doom Toad" },
    [17440962] = { nm_slug = "Baron_Vapula", zone = "Castle Zvahl Keep", placeholder_name = "Demon Wizard" },
    [17440968] = { nm_slug = "Count_Bifrons", zone = "Castle Zvahl Keep", placeholder_name = "Demon Knight" },
    [17440973] = { nm_slug = "Viscount_Morax", zone = "Castle Zvahl Keep", placeholder_name = "Demon Warlock" },
    [17440985] = { nm_slug = "Baronet_Romwe", zone = "Castle Zvahl Keep", placeholder_name = "Demon Pawn" },
    [17461306] = { nm_slug = "Sewer_Syrup", zone = "Bostaunieux Oubliette", placeholder_name = "Mousse" },
    [17461432] = { nm_slug = "Arioch", zone = "Bostaunieux Oubliette", placeholder_name = "Werebat" },
    [17486030] = { nm_slug = "Falcatus_Aranei", zone = "Korroloka Tunnel", placeholder_name = "Huge Spider" },
    [17486035] = { nm_slug = "Falcatus_Aranei", zone = "Korroloka Tunnel", placeholder_name = "Huge Spider" },
    [17486128] = { nm_slug = "Dame_Blanche", zone = "Korroloka Tunnel", placeholder_name = "Bogy" },
    [17489979] = { nm_slug = "Sabotender_Mariachi", zone = "Kuftal Tunnel", placeholder_name = "Sabotender Sediendo" },
    [17489986] = { nm_slug = "Sabotender_Mariachi", zone = "Kuftal Tunnel", placeholder_name = "Sabotender Sediendo" },
    [17490002] = { nm_slug = "Amemet", zone = "Kuftal Tunnel", placeholder_name = "Sand Lizard" },
    [17490015] = { nm_slug = "Amemet", zone = "Kuftal Tunnel", placeholder_name = "Sand Lizard" },
    [17490158] = { nm_slug = "Bloodthirster_Madkix", zone = "Kuftal Tunnel", placeholder_name = "Goblin Mercenary" },
    [17490212] = { nm_slug = "Arachne", zone = "Kuftal Tunnel", placeholder_name = "Recluse Spider" },
    [17490216] = { nm_slug = "Arachne", zone = "Kuftal Tunnel", placeholder_name = "Recluse Spider" },
    [17490220] = { nm_slug = "Arachne", zone = "Kuftal Tunnel", placeholder_name = "Recluse Spider" },
    [17498156] = { nm_slug = "Masan", zone = "Sea Serpent Grotto", placeholder_name = "Royal Leech" },
    [17498178] = { nm_slug = "Namtar", zone = "Sea Serpent Grotto", placeholder_name = "Ghast Blm" },
    [17498183] = { nm_slug = "Namtar", zone = "Sea Serpent Grotto", placeholder_name = "Ghast Blm" },
    [17498280] = { nm_slug = "Qull_The_Shellbuster", zone = "Sea Serpent Grotto", placeholder_name = "Brook Sahagin" },
    [17498283] = { nm_slug = "Qull_The_Shellbuster", zone = "Sea Serpent Grotto", placeholder_name = "Brook Sahagin" },
    [17498355] = { nm_slug = "Mouu_The_Waverider", zone = "Sea Serpent Grotto", placeholder_name = "Bog Sahagin" },
    [17498410] = { nm_slug = "Worr_The_Clawfisted", zone = "Sea Serpent Grotto", placeholder_name = "Marsh Sahagin" },
    [17498418] = { nm_slug = "Sea_Hog", zone = "Sea Serpent Grotto", placeholder_name = "Razorjaw Pugil" },
    [17498419] = { nm_slug = "Sea_Hog", zone = "Sea Serpent Grotto", placeholder_name = "Razorjaw Pugil" },
    [17498426] = { nm_slug = "Voll_The_Sharkfinned", zone = "Sea Serpent Grotto", placeholder_name = "Marsh Sahagin" },
    [17498434] = { nm_slug = "Yarr_The_Pearleyed", zone = "Sea Serpent Grotto", placeholder_name = "Lagoon Sahagin" },
    [17498444] = { nm_slug = "Novv_The_Whitehearted", zone = "Sea Serpent Grotto", placeholder_name = "Lagoon Sahagin" },
    [17498513] = { nm_slug = "Zuug_The_Shoreleaper", zone = "Sea Serpent Grotto", placeholder_name = "Delta Sahagin" },
    [17498518] = { nm_slug = "Charybdis", zone = "Sea Serpent Grotto", placeholder_name = "Devil Manta" },
    [17498521] = { nm_slug = "Charybdis", zone = "Sea Serpent Grotto", placeholder_name = "Devil Manta" },
    [17530882] = { nm_slug = "Epialtes", zone = "Lower Delkfutt's Tower", placeholder_name = "Giant Gatekeeper" },
    [17547275] = { nm_slug = "Gabblox_Magpietongue", zone = "Dynamis - Jeuno", placeholder_name = "Vanguard Armorer" },
    [17547289] = { nm_slug = "Tufflix_Loglimbs", zone = "Dynamis - Jeuno", placeholder_name = "Vanguard Armorer" },
    [17547292] = { nm_slug = "Cloktix_Longnail", zone = "Dynamis - Jeuno", placeholder_name = "Vanguard Armorer" },
    [17547452] = { nm_slug = "Rutrix_Hamgams", zone = "Dynamis - Jeuno", placeholder_name = "Vanguard Dragontamer" },
    [17547469] = { nm_slug = "Anvilix_Sootwrists", zone = "Dynamis - Jeuno", placeholder_name = "Vanguard Smithy" },
    [17547470] = { nm_slug = "Bootrix_Jaggedelbow", zone = "Dynamis - Jeuno", placeholder_name = "Vanguard Pitfighter" },
    [17547471] = { nm_slug = "Mobpix_Mucousmouth", zone = "Dynamis - Jeuno", placeholder_name = "Vanguard Welldigger" },
    [17547475] = { nm_slug = "Distilix_Stickytoes", zone = "Dynamis - Jeuno", placeholder_name = "Vanguard Alchemist" },
    [17547477] = { nm_slug = "Jabbrox_Grannyguise", zone = "Dynamis - Jeuno", placeholder_name = "Vanguard Enchanter" },
    [17547481] = { nm_slug = "Scruffix_Shaggychest", zone = "Dynamis - Jeuno", placeholder_name = "Vanguard Armorer" },
    [17547483] = { nm_slug = "Blazox_Boneybod", zone = "Dynamis - Jeuno", placeholder_name = "Vanguard Pathfinder" },
    [17563783] = { nm_slug = "Slendlix_Spindlethumb", zone = "Inner Horutoto Ruins", placeholder_name = "Goblin Leecher" },
    [17576053] = { nm_slug = "Cwn_Cyrff", zone = "The Eldieme Necropolis", placeholder_name = "Tomb Wolf" },
    [17584397] = { nm_slug = "Demonic_Tiphia", zone = "Crawlers' Nest", placeholder_name = "Wespe CN" },
    [17613044] = { nm_slug = "Goliath", zone = "Fei'Yin", placeholder_name = "Colossus" },
    [17613046] = { nm_slug = "Goliath", zone = "Fei'Yin", placeholder_name = "Colossus" },
    [17613048] = { nm_slug = "Goliath", zone = "Fei'Yin", placeholder_name = "Colossus" },
    [17613049] = { nm_slug = "Goliath", zone = "Fei'Yin", placeholder_name = "Colossus" },
    [17613050] = { nm_slug = "Goliath", zone = "Fei'Yin", placeholder_name = "Colossus" },
    [17613052] = { nm_slug = "Goliath", zone = "Fei'Yin", placeholder_name = "Colossus" },
    [17613054] = { nm_slug = "Goliath", zone = "Fei'Yin", placeholder_name = "Colossus" },
    [17613098] = { nm_slug = "Northern_Shadow", zone = "Fei'Yin", placeholder_name = "Specter War" },
    [17613108] = { nm_slug = "Eastern_Shadow", zone = "Fei'Yin", placeholder_name = "Specter Thf" },
    [17613117] = { nm_slug = "Southern_Shadow", zone = "Fei'Yin", placeholder_name = "Specter Blm" },
    [17616996] = { nm_slug = "Tyrannic_Tunnok", zone = "Ifrit's Cauldron", placeholder_name = "Sulfur Scorpion" },
    [17617001] = { nm_slug = "Tyrannic_Tunnok", zone = "Ifrit's Cauldron", placeholder_name = "Sulfur Scorpion" },
    [17617055] = { nm_slug = "Foreseer_Oramix", zone = "Ifrit's Cauldron", placeholder_name = "Goblin Alchemist" },
    [17617056] = { nm_slug = "Foreseer_Oramix", zone = "Ifrit's Cauldron", placeholder_name = "Goblin Alchemist" },
    [17617066] = { nm_slug = "Foreseer_Oramix", zone = "Ifrit's Cauldron", placeholder_name = "Goblin Alchemist" },
    [17617069] = { nm_slug = "Foreseer_Oramix", zone = "Ifrit's Cauldron", placeholder_name = "Goblin Alchemist" },
    [17617118] = { nm_slug = "Vouivre", zone = "Ifrit's Cauldron", placeholder_name = "Hurricane Wyvern" },
    [17617122] = { nm_slug = "Vouivre", zone = "Ifrit's Cauldron", placeholder_name = "Hurricane Wyvern" },
    [17629237] = { nm_slug = "Centurio_X-I", zone = "Quicksand Caves", placeholder_name = "Antican Signifer" },
    [17629262] = { nm_slug = "Sabotender_Bailarin", zone = "Quicksand Caves", placeholder_name = "Sabotender Bailaor" },
    [17629280] = { nm_slug = "Antican_Praefectus", zone = "Quicksand Caves", placeholder_name = "Antican Princeps" },
    [17629296] = { nm_slug = "Sagittarius_X-XIII", zone = "Quicksand Caves", placeholder_name = "Antican Princeps" },
    [17629397] = { nm_slug = "Nussknacker", zone = "Quicksand Caves", placeholder_name = "Sand Lizard" },
    [17629409] = { nm_slug = "Antican_Magister", zone = "Quicksand Caves", placeholder_name = "Antican Hastatus" },
    [17629420] = { nm_slug = "Antican_Proconsul", zone = "Quicksand Caves", placeholder_name = "Antican Signifer" },
    [17629433] = { nm_slug = "Diamond_Daig", zone = "Quicksand Caves", placeholder_name = "Helm Beetle" },
    [17629436] = { nm_slug = "Diamond_Daig", zone = "Quicksand Caves", placeholder_name = "Helm Beetle" },
    [17629439] = { nm_slug = "Diamond_Daig", zone = "Quicksand Caves", placeholder_name = "Helm Beetle" },
    [17629442] = { nm_slug = "Diamond_Daig", zone = "Quicksand Caves", placeholder_name = "Helm Beetle" },
    [17629446] = { nm_slug = "Diamond_Daig", zone = "Quicksand Caves", placeholder_name = "Helm Beetle" },
    [17629480] = { nm_slug = "Antican_Tribunus", zone = "Quicksand Caves", placeholder_name = "Antican Aedilis" },
    [17629557] = { nm_slug = "Hastatus_XI-XII", zone = "Quicksand Caves", placeholder_name = "Antican Triarius" },
    [17629582] = { nm_slug = "Sabotender_Bailarina", zone = "Quicksand Caves", placeholder_name = "Spelunking Sabotender" },
    [17629586] = { nm_slug = "Sabotender_Bailarina", zone = "Quicksand Caves", placeholder_name = "Spelunking Sabotender" },
    [17629590] = { nm_slug = "Sabotender_Bailarina", zone = "Quicksand Caves", placeholder_name = "Spelunking Sabotender" },
    [17645605] = { nm_slug = "Goblinsavior_Heronox", zone = "Gustav Tunnel", placeholder_name = "Goblin Reaper" },
    [17645633] = { nm_slug = "Wyvernpoacher_Drachlox", zone = "Gustav Tunnel", placeholder_name = "Goblin Mercenary" },
    [17645718] = { nm_slug = "Baobhan_Sith", zone = "Gustav Tunnel", placeholder_name = "Erlik" },
    [17645738] = { nm_slug = "Taxim", zone = "Gustav Tunnel", placeholder_name = "Doom Warlock" },
    [17645768] = { nm_slug = "Amikiri", zone = "Gustav Tunnel", placeholder_name = "Antares GT" },
    [17645772] = { nm_slug = "Amikiri", zone = "Gustav Tunnel", placeholder_name = "Antares GT" },
    [17649730] = { nm_slug = "Lord_Of_Onzozo", zone = "Labyrinth of Onzozo", placeholder_name = "Flying Manta" },
    [17649783] = { nm_slug = "Narasimha", zone = "Labyrinth of Onzozo", placeholder_name = "Labyrinth Manticore" },
    [17649787] = { nm_slug = "Narasimha", zone = "Labyrinth of Onzozo", placeholder_name = "Labyrinth Manticore" },
    [17649797] = { nm_slug = "Hellion", zone = "Labyrinth of Onzozo", placeholder_name = "Tainted Flesh LoO" },
    [17649817] = { nm_slug = "Ose", zone = "Labyrinth of Onzozo", placeholder_name = "Torama" },
    [17649820] = { nm_slug = "Ose", zone = "Labyrinth of Onzozo", placeholder_name = "Torama" },
    [17649829] = { nm_slug = "Soulstealer_Skullnix", zone = "Labyrinth of Onzozo", placeholder_name = "Goblin Alchemist" },
    [17649837] = { nm_slug = "Soulstealer_Skullnix", zone = "Labyrinth of Onzozo", placeholder_name = "Goblin Bandit" },
    [17678346] = { nm_slug = "Sea_Horror", zone = "Ship bound for Selbina", placeholder_name = "Sea Monk" },
    [17682442] = { nm_slug = "Sea_Horror", zone = "Ship bound for Mhaura", placeholder_name = "Sea Monk" },
}
